### ISSUE TITLE
Build status doesn't change from BUILDING when minio task fails

### ISSUE THREAD

**Issue by dlim716** [conda-incubator/conda-store#171]
I noticed that the status of a bulid does not get updated from BUILDING to FAILED when a minio task fails.
I pasted a traceback of the minio failure below. I saw the same behavior when incorrect s3 credentials were passed to minio and the task had failed. You should be able to reproduce this issue by setting incorrect s3 credentials in the conda store settings. There doesn't seem a way to cancel a build, so I had to manually delete the record from the build table.

Traceback (most recent call last):
  File "/opt/conda-store-server/conda_store_server/build.py", line 175, in build_conda_environment
    set_build_completed(conda_store, build, output.encode("utf-8"), packages)
  File "/opt/conda-store-server/conda_store_server/build.py", line 79, in set_build_completed
    conda_store.storage.set(
  File "/opt/conda-store-server/conda_store_server/storage.py", line 133, in set
    self.internal_client.put_object(
  File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/minio/api.py", line 1787, in put_object
    raise exc
  File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/minio/api.py", line 1741, in put_object
    return self._put_object(
  File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/minio/api.py", line 1598, in _put_object
    response = self._execute(
  File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/minio/api.py", line 406, in _execute
    return self._url_open(
  File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/minio/api.py", line 389, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: XMinioStorageFull, message: Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed., resource: /conda-store/logs/448a12f002aac20ba1673d5de067377bbf66c2d4ac0a039c74642a62ac1bdb88-20210924-164948-645244-11-maria-test3.log, request_id: 16A7D07DFCBB6581, host_id: f2778deb-a65a-4ba5-b52a-cde414bcac2e, bucket_name: conda-store, object_name: logs/448a12f002aac20ba1673d5de067377bbf66c2d4ac0a039c74642a62ac1bdb88-20210924-164948-645244-11-maria-test3.log

**Comment by costrouc** [comment]
My hypothesis on this error is that the build is failing and then triggers https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/build.py#L176-L183. But the ` set_build_failed` does not work since s3 credentials are not set and then causes another exception to be raised.

**Comment by kcpevey** [comment]
@costrouc is this still valid?
