### ISSUE TITLE
Can't use a Nexus channel that does not expose channeldata.json

### ISSUE THREAD

**Issue by dpfeif** [conda-incubator/conda-store#414]
# Steps to reproduce

- Set a Nexus conda channel that does not expose `channeldata.json` in the config file, e.g., `c.CondaStore.conda_default_channels = ["https://some-public-nexus.com/nexus/repository/some-public-conda-group/"]`
- Run `conda-store-server --config <the-file-above>`

# Error message

```
Traceback (most recent call last):
  File "/home/jovyan/.conda/envs/inno22Q4/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/jovyan/.conda/envs/inno22Q4/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/jovyan/.conda/envs/inno22Q4/lib/python3.10/site-packages/conda_store_server/worker/tasks.py", line 72, in task_update_conda_channels
    channel.update_packages(conda_store.db, subdirs=conda_store.conda_platforms)
  File "/home/jovyan/.conda/envs/inno22Q4/lib/python3.10/site-packages/conda_store_server/orm.py", line 288, in update_packages
    repodata = download_repodata(self.name, self.last_update, subdirs=subdirs)
  File "/home/jovyan/.conda/envs/inno22Q4/lib/python3.10/site-packages/conda_store_server/conda.py", line 149, in download_repodata
    response.raise_for_status()
  File "/home/jovyan/.conda/envs/inno22Q4/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://.../channeldata.json
```

# Motivation

I know that conda/mamba also checks for this `channeldata.json` when installing packages, but they don't stop when it's missing. We've been able to install packages from this channel without any issue. 

# Proposed solution

The line that raises an exception is https://github.com/Quansight/conda-store/blob/795c889f3d3e15f398634be673c03a3f0cba8e98/conda-store-server/conda_store_server/conda.py#L149

One way around this would be to check for 404 like 304 is currently checked, and continue with `repodata = {}` in that case instead of raising an exception. I'm happy to open a PR if this fits the design of the product.

**Comment by costrouc** [comment]
@dpfeif thanks for the issue. There is issue https://github.com/Quansight/conda-store/issues/441 which I think should long term properly fix this. I am trying to move conda-store away from hand rolling conda api calls and instead depend on conda directly to ensure that this works long term.

Also in the meantime I would be happy to accept that PR as a workaround for internal nexus channels.

**Comment by peytondmurray** [comment]
Closing as #441 should resolve this.
