### ISSUE TITLE
FileNotFoundError on `task_build_conda_docker`

### ISSUE THREAD

**Issue by ranchodeluxe** [conda-incubator/conda-store#426]
Hello ✨
Nice work on this project! It's exactly what I'm looking for. I'm so close to getting this working on a jupyterhub k8 cluster. Just having a problem with the last artifact build – the docker image in `task_build_conda_docker`

*server/worker image* : `Quansight/conda-store-server:v0.4.12`

*conda_store_config.py*: see below

### Problem

The important part of the worker traceback is below and related to `conda-docker`:

```python
Traceback (most recent call last):
  File "/opt/conda/envs/conda-store-server/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/conda-store-server/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda-store-server/conda_store_server/worker/tasks.py", line 181, in task_build_conda_docker
    build_conda_docker(conda_store, build)
  File "/opt/conda-store-server/conda_store_server/build.py", line 341, in build_conda_docker
    image = build_docker_environment_image(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/conda-store-server/lib/python3.11/site-packages/conda_docker/conda.py", line 677, in build_docker_environment_ima
ge  
    add_conda_layers(
  File "/opt/conda/envs/conda-store-server/lib/python3.11/site-packages/conda_docker/conda.py", line 590, in add_conda_layers
    add_conda_package_layers(
  File "/opt/conda/envs/conda-store-server/lib/python3.11/site-packages/conda_docker/conda.py", line 557, in add_conda_package_layers
    with open(meta_path) as f:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmphi2_ai7h/opt/conda/conda-meta/_libgcc_mutex-0.1-conda_forge.json'
```

### Config

```bash
apiVersion: v1
kind: ConfigMap
metadata:
  name: conda-store-config-67hfbmckm9
  namespace: daskhub
data:
  conda_store_config.py: |
    import logging

    from conda_store_server.storage import S3Storage
    from conda_store_server.server.auth import DummyAuthentication
    from conda_store_server.schema import Permissions
    from python_docker.registry import Registry
    import os

    # ==================================
    #      conda-store settings
    # ==================================
    c.CondaStore.storage_class = S3Storage
    c.CondaStore.store_directory = "/opt/conda-store/conda-store/"
    c.CondaStore.database_url = "postgresql+psycopg2://admin:password@postgres/conda-store"
    c.CondaStore.redis_url = "redis://redis:6379/0"
    c.CondaStore.default_uid = 1000
    c.CondaStore.default_gid = 1000
    c.CondaStore.default_permissions = "775"

    c.S3Storage.internal_endpoint = "minio:9000"
    c.S3Storage.internal_secure = False
    c.S3Storage.external_endpoint = "localhost:30900"
    c.S3Storage.external_secure = False
    c.S3Storage.access_key = "admin"
    c.S3Storage.secret_key = "password"
    c.S3Storage.region = "us-west-2"  # minio region default
    c.S3Storage.bucket_name = "conda-store"

    # ==================================
    #        server settings
    # ==================================
    c.CondaStoreServer.log_level = logging.DEBUG
    c.CondaStoreServer.enable_ui = True
    c.CondaStoreServer.enable_api = True
    c.CondaStoreServer.enable_registry = True
    c.CondaStoreServer.enable_metrics = True
    c.CondaStoreServer.address = "0.0.0.0"
    c.CondaStoreServer.port = 5000
    # This MUST start with `/`
    c.CondaStoreServer.url_prefix = "/"


    # ==================================
    #         auth settings
    # ==================================
    c.CondaStoreServer.authentication_class = DummyAuthentication
    c.DummyAuthentication.password = "badjuju"
    c.AuthenticationBackend.predefined_tokens = {'default': {'primary_namespace': 'default', 'role_bindings': {'*/*': ['admin']}}}
    c.RBACAuthorizationBackend.unauthenticated_role_bindings = {"*/*": {"admin"}}
    c.RBACAuthorizationBackend.authenticated_role_bindings = {"*/*": {"admin"}}


    # ==================================
    #         docker registry
    # ==================================
    def _configure_docker_registry(registry_url: str):
        return Registry(
            'https://registry-1.docker.io',
            username=os.environ.get('DOCKER_USERNAME'),
            password=os.environ.get('DOCKER_PASSWORD')
        )

    c.ContainerRegistry.container_registries = {
        'https://registry-1.docker.io': _configure_docker_registry
    }


    # ==================================
    #         worker settings
    # ==================================
    c.CondaStoreWorker.log_level = logging.INFO
    c.CondaStoreWorker.watch_paths = ["/opt/environments"]
    c.CondaStoreWorker.concurrency = 2
```

**Comment by ranchodeluxe** [comment]
Okay, was able to reproduce the error from inside the worker container given that the all the tasks before `task_build_conda_docker` succeeded and the previous artifacts are on disk:

showing build artifacts before `task_build_conda_docker`:
```bash
I have no name!@conda-store-worker-567bf5d4f-rt8w8:/var/lib/conda-store$ ls -lah /opt/conda-store/conda-store/
total 12K
drwxr-sr-x 3 1000 1000 4.0K Jan 25 17:06 .
drwxrwsr-x 4 1000 1000 4.0K Jan 25 17:04 ..
drwxr-sr-x 4 1000 1000 4.0K Jan 25 17:07 default
I have no name!@conda-store-worker-567bf5d4f-rt8w8:/var/lib/conda-store$ ls -lah /opt/conda-store/conda-store/default/
total 16K
drwxr-sr-x  4 1000 1000 4.0K Jan 25 17:07 .
drwxr-sr-x  3 1000 1000 4.0K Jan 25 17:06 ..
drwxrwsr-x 12 1000 1000 4.0K Jan 25 23:58 b6aaec56327505b205619b744f89d6427099a30540f6a35eb4732f9d0d1f8ae6-20230125-170643-265989-8-projectkubeenv3
drwxr-sr-x  2 1000 1000 4.0K Jan 25 17:07 envs
I have no name!@conda-store-worker-567bf5d4f-rt8w8:/var/lib/conda-store$ ls -lah /opt/conda-store/conda-store/default/b6aaec56327505b205619b744f89d6427099a30540f6a35eb4732f9d0d1f8ae6-20230125-170643-265989-8-projectkubeenv3/
total 48K
drwxrwsr-x 12 1000 1000 4.0K Jan 25 23:58 .
drwxr-sr-x  4 1000 1000 4.0K Jan 25 17:07 ..
drwxrwsr-x  2 1000 1000 4.0K Jan 25 17:07 bin
drwxrwsr-x  2 1000 1000 4.0K Jan 25 17:07 compiler_compat
drwxrwsr-x  2 1000 1000 4.0K Jan 25 17:07 conda-meta
drwxrwsr-x 10 1000 1000 4.0K Jan 25 17:07 include
drwxrwsr-x 14 1000 1000 4.0K Jan 25 17:07 lib
drwxrwsr-x  3 1000 1000 4.0K Jan 25 17:07 man
drwxrwsr-x 10 1000 1000 4.0K Jan 25 17:07 share
drwxrwsr-x  3 1000 1000 4.0K Jan 25 17:07 ssl
drwxrwsr-x  3 1000 1000 4.0K Jan 25 17:07 x86_64-conda-linux-gnu
drwxrwsr-x  3 1000 1000 4.0K Jan 25 17:07 x86_64-conda_cos6-linux-gnu
I have no name!@conda-store-worker-567bf5d4f-rt8w8:/var/lib/conda-store$ ls -lah /opt/conda-store/conda-store/default/envs/
total 12K
drwxr-sr-x 2 1000 1000 4.0K Jan 25 17:07 .
drwxr-sr-x 4 1000 1000 4.0K Jan 25 17:07 ..
lrwxrwxrwx 1 1000 1000  142 Jan 25 17:07 projectkubeenv3 -> /opt/conda-store/conda-store/default/b6aaec56327505b205619b744f89d6427099a30540f6a35eb4732f9d0d1f8ae6-20230125-170643-265989-8-projectkubeenv3
I have no name!@conda-store-worker-567bf5d4f-rt8w8:/var/lib/conda-store$ 
```

Rerunning error code from shell
```python
I have no name!@conda-store-worker-567bf5d4f-rt8w8:/var/lib/conda-store$ python3                                                           [349/349]
Python 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0] on linux                                                       
Type "help", "copyright", "credits" or "license" for more information.                                                                              
>>> from conda_store_server import api, conda, orm, utils, schema                                                                                   
>>> from conda_store_server.worker.app import CondaStoreWorker                                                                                      
>>> from conda_store_server.worker.tasks import WorkerTask                                                                                          
>>> from conda_store_server.build import build_conda_docker                                                                                         
>>> CondaStoreWorker.config_file = '/etc/conda-store/conda_store_config.py'                                                                         
>>> task = WorkerTask()                                                                                                                             
>>> session = orm.new_session_factory("postgresql+psycopg2://admin:password@postgres/conda-store")                                                  
>>> build = session.query(orm.Build).filter(orm.Build.id == 8).first()                                                                              
>>> build_conda_docker(task.worker.conda_store, build) 

[CondaStoreWorker] creating docker archive of conda environment=/opt/conda-store/conda-store/default/b6aaec56327505b205619b744f89d6427099a30540f6a35eb4732f9d0d1f8ae6-20230125-170643-265989-8-projectkubeenv3  

Traceback (most recent call last):
  File "<stdin>", line 1, in <module> 
  File "/opt/conda-store-server/conda_store_server/build.py", line 356, in build_conda_docker
    image = build_docker_environment_image(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/conda-store-server/lib/python3.11/site-packages/conda_docker/conda.py", line 677, in build_docker_environment_image
    add_conda_layers(
  File "/opt/conda/envs/conda-store-server/lib/python3.11/site-packages/conda_docker/conda.py", line 590, in add_conda_layers
    add_conda_package_layers(
  File "/opt/conda/envs/conda-store-server/lib/python3.11/site-packages/conda_docker/conda.py", line 557, in add_conda_package_layers
    with open(meta_path) as f:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpkw_0x_si/opt/conda/conda-meta/_libgcc_mutex-0.1-conda_forge.json'
```

**Comment by ranchodeluxe** [comment]
I now see `conda-store==v0.4.5` uses `conda-docker==v0.0.3` and it gets a bit further because `add_conda_package_layers` is using older logic around `repodata_record.json` to resolve package meta. 

But this makes me wonder if folks are actually using the following build artifacts `(schema.BuildArtifactType.DOCKER_MANIFEST, schema.BuildArtifactType.CONTAINER_REGISTRY)` in versions > `v0.4.5`?

I can't imagine I'm the only one running into this given that the `/tmp/<random>/opt/conda/conda-meta/*.json` files are not there

**Comment by costrouc** [comment]
@ranchodeluxe I haven't had a great time trying to debug the docker build issues and am finding that docker images builds are failing quite frequently. This is something on conda-docker that needs to be resolved.

**Comment by peytondmurray** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple `conda-store` releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier ☹️

Cheers!
