### ISSUE TITLE
CLI error handling for improved user experience

### ISSUE THREAD

**Issue by leej3** [conda-incubator/conda-store#461]
The conda-store cli should handle the following usage more gracefully.   I believe I have a fix for the first issue. The latter two should likely be fixed by having a check early on where the route conda-store/api/v1/ is hit. Failure should be reported to the user along with the exact url that was tested.

* When run with no arguments

<details>
<summary>conda-store</summary>
<br>

```
Traceback (most recent call last):
  File "/home/lee/mambaforge/envs/conda-store-server-dev/bin/conda-store", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/lee/temp/conda-store/conda-store/conda_store/__main__.py", line 38, in main
    detect_shebang()
  File "/home/lee/temp/conda-store/conda-store/conda_store/__main__.py", line 16, in detect_shebang
    filename = pathlib.Path(sys.argv[1]).resolve()
                            ~~~~~~~~^^^
IndexError: list index out of range
```

</details>

* When run without the url configured

<details>
<summary>conda-store  list build</summary>
<br>

```
Traceback (most recent call last):
  File "/home/lee/mambaforge/envs/conda-store-server-dev/bin/conda-store", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/lee/temp/conda-store/conda-store/conda_store/__main__.py", line 42, in main
    cli()
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/temp/conda-store/conda-store/conda_store/utils.py", line 21, in wrapper
    return asyncio.run(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/lee/temp/conda-store/conda-store/conda_store/cli.py", line 387, in list_build
    builds = await conda_store.list_builds(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/temp/conda-store/conda-store/conda_store/api.py", line 177, in list_builds
    return await self.get_paginated_request(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/temp/conda-store/conda-store/conda_store/api.py", line 54, in get_paginated_request
    num_pages = math.ceil(response_data["count"] / response_data["size"])
                          ~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'count'
```

</details>

* When run without a server running

<details>
<summary>conda-store --conda-store-url=http://localhost:5000/conda-store list build</summary>
<br>

```
Traceback (most recent call last):
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 5000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lee/mambaforge/envs/conda-store-server-dev/bin/conda-store", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/lee/temp/conda-store/conda-store/conda_store/__main__.py", line 39, in main
    cli()
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/temp/conda-store/conda-store/conda_store/utils.py", line 21, in wrapper
    return asyncio.run(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/lee/temp/conda-store/conda-store/conda_store/cli.py", line 387, in list_build
    builds = await conda_store.list_builds(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/temp/conda-store/conda-store/conda_store/api.py", line 177, in list_builds
    return await self.get_paginated_request(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/temp/conda-store/conda-store/conda_store/api.py", line 52, in get_paginated_request
    async with self.session.get(url) as response:
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/mambaforge/envs/conda-store-server-dev/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:5000 ssl:default [Connect call failed ('127.0.0.1', 5000)]
```

</details>

**Comment by costrouc** [comment]
@leej3 I agree with your comments above. 

I'd suggest with no arguments it should be displaying the `--help`

Like you said for `conda-store list build` and other related methods which call the conda-store-server api we need a precheck. `<conda-store-url>/api/v1/` should be sufficient. If this url responds then it is a valid server.

**Comment by trallard** [comment]
I am going to mark this as blocked until we define #461

**Comment by kcpevey** [comment]
@trallard you've inadvertently tagged THIS issue in your comment above. Which one were you intending to tag?

**Comment by trallard** [comment]
It was this https://github.com/conda-incubator/conda-store/issues/248 but the issue is now closed. 
need to open another issue to redesign/rethink the CLI as a whole.
