### ISSUE TITLE
Invalid conda channel will block all kernel builds

### ISSUE THREAD

**Issue by totycro** [conda-incubator/conda-store#515]
When a user specifies a conda channel that doesn't exist, apparently all future kernel builds are blocked.

On startup the conda store worker will print this error message:
```
qhub-conda-store-worker-5bcc66c9f7-vj72n conda-store-worker Traceback (most recent call last):
qhub-conda-store-worker-5bcc66c9f7-vj72n conda-store-worker   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
qhub-conda-store-worker-5bcc66c9f7-vj72n conda-store-worker     R = retval = fun(*args, **kwargs)
qhub-conda-store-worker-5bcc66c9f7-vj72n conda-store-worker   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
qhub-conda-store-worker-5bcc66c9f7-vj72n conda-store-worker     return self.run(*args, **kwargs)
qhub-conda-store-worker-5bcc66c9f7-vj72n conda-store-worker   File "/opt/conda-store-server/conda_store_server/worker/tasks.py", line 72, in task_update_conda_channels
qhub-conda-store-worker-5bcc66c9f7-vj72n conda-store-worker     channel.update_packages(conda_store.db, subdirs=conda_store.conda_platforms)
qhub-conda-store-worker-5bcc66c9f7-vj72n conda-store-worker   File "/opt/conda-store-server/conda_store_server/orm.py", line 288, in update_packages
qhub-conda-store-worker-5bcc66c9f7-vj72n conda-store-worker     repodata = download_repodata(self.name, self.last_update, subdirs=subdirs)
qhub-conda-store-worker-5bcc66c9f7-vj72n conda-store-worker   File "/opt/conda-store-server/conda_store_server/conda.py", line 149, in download_repodata
qhub-conda-store-worker-5bcc66c9f7-vj72n conda-store-worker     response.raise_for_status()
qhub-conda-store-worker-5bcc66c9f7-vj72n conda-store-worker   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
qhub-conda-store-worker-5bcc66c9f7-vj72n conda-store-worker     raise HTTPError(http_error_msg, response=self)
qhub-conda-store-worker-5bcc66c9f7-vj72n conda-store-worker requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/THE_INVALID_CHANNEL/channeldata.json
```

This happens with this docker image for the worker: `quansight/conda-store-server:v0.4.12`

Usually when builds get stuck then it's enough to restart the conda store worker, but in this case this wasn't enough.

It does now build again after manually removing the offending entry from the `conda_channels` table in the database.

**Comment by trallard** [comment]
Thanks for reporting this issue @totycro - I think we will need to do some further investigation on our end (we also have other issues like #299 that might be somewhat related)
