### ISSUE TITLE
[BUG] - Tests fail if you pass arguments to pytest

### ISSUE THREAD

**Issue by asmeurer** [conda-incubator/conda-store#538]
### Describe the bug

If you run the tests with pytest and try to pass arguments to pytest, like `-v`, you get a bunch of failures like

```
---------------------------------------------------------------------------------------------------- Captured stderr call ----------------------------------------------------------------------------------------------------
usage: pytest [-h] [--standalone] [--config CondaStoreWorker.config_file]
              [extra_args ...]
pytest: error: argument -v: expected one argument
Restoring 1 unacknowledged message(s)
----------------------------------------------------------------------------------------------------- Captured log call ------------------------------------------------------------------------------------------------------
CRITICAL celery.worker:worker.py:206 Unrecoverable error: TypeError('cannot unpack non-iterable ExceptionInfo object')
Traceback (most recent call last):
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/argparse.py", line 1853, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/argparse.py", line 2062, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/argparse.py", line 1992, in consume_optional
    arg_count = match_argument(action, selected_patterns)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/argparse.py", line 2157, in _match_argument
    raise ArgumentError(action, msg)
argparse.ArgumentError: argument -v: expected one argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/concurrency/base.py", line 30, in apply_target
    ret = target(*args, **kwargs)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/app/trace.py", line 654, in trace_task_ret
    R, I, T, Rstr = trace_task(app.tasks[name],
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/app/trace.py", line 610, in trace_task
    return task.__trace__(uuid, args, kwargs, request)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/aaronmeurer/Documents/conda-store/conda-store-server/conda_store_server/worker/tasks.py", line 174, in task_solve_conda_environment
    conda_store = self.worker.conda_store
  File "/home/aaronmeurer/Documents/conda-store/conda-store-server/conda_store_server/worker/tasks.py", line 45, in worker
    self._worker.initialize()
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
  File "/home/aaronmeurer/Documents/conda-store/conda-store-server/conda_store_server/worker/app.py", line 63, in initialize
    super().initialize(*args, **kwargs)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/traitlets/config/application.py", line 465, in initialize
    self.parse_command_line(argv)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/traitlets/config/application.py", line 880, in parse_command_line
    self.cli_config = deepcopy(loader.load_config())
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/traitlets/config/loader.py", line 884, in load_config
    self._parse_args(argv)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/traitlets/config/loader.py", line 945, in _parse_args
    self.parsed_data = self.parser.parse_args(to_parse)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/argparse.py", line 1820, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/traitlets/config/loader.py", line 784, in parse_known_args
    return super().parse_known_args(args, namespace)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/argparse.py", line 1856, in parse_known_args
    self.error(str(err))
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/argparse.py", line 2577, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/argparse.py", line 2564, in exit
    _sys.exit(status)
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/concurrency/base.py", line 39, in apply_target
    reraise(WorkerLostError, WorkerLostError(repr(exc)),
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/exceptions.py", line 109, in reraise
    raise value.with_traceback(tb)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/concurrency/base.py", line 30, in apply_target
    ret = target(*args, **kwargs)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/app/trace.py", line 654, in trace_task_ret
    R, I, T, Rstr = trace_task(app.tasks[name],
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/app/trace.py", line 610, in trace_task
    return task.__trace__(uuid, args, kwargs, request)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/aaronmeurer/Documents/conda-store/conda-store-server/conda_store_server/worker/tasks.py", line 174, in task_solve_conda_environment
    conda_store = self.worker.conda_store
  File "/home/aaronmeurer/Documents/conda-store/conda-store-server/conda_store_server/worker/tasks.py", line 45, in worker
    self._worker.initialize()
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
  File "/home/aaronmeurer/Documents/conda-store/conda-store-server/conda_store_server/worker/app.py", line 63, in initialize
    super().initialize(*args, **kwargs)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/traitlets/config/application.py", line 465, in initialize
    self.parse_command_line(argv)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/traitlets/config/application.py", line 880, in parse_command_line
    self.cli_config = deepcopy(loader.load_config())
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/traitlets/config/loader.py", line 884, in load_config
    self._parse_args(argv)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/traitlets/config/loader.py", line 945, in _parse_args
    self.parsed_data = self.parser.parse_args(to_parse)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/argparse.py", line 1820, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/traitlets/config/loader.py", line 784, in parse_known_args
    return super().parse_known_args(args, namespace)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/argparse.py", line 1856, in parse_known_args
    self.error(str(err))
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/argparse.py", line 2577, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/argparse.py", line 2564, in exit
    _sys.exit(status)
billiard.exceptions.WorkerLostError: SystemExit(2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 336, in start
    blueprint.start(self)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 726, in start
    c.loop(*c.loop_args())
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/worker/loops.py", line 130, in synloop
    connection.drain_events(timeout=2.0)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/kombu/connection.py", line 341, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 997, in drain_events
    get(self._deliver, timeout=timeout)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/kombu/utils/scheduling.py", line 55, in get
    return self.fun(resource, callback, **kwargs)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 1035, in _drain_channel
    return channel.drain_events(callback=callback, timeout=timeout)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 754, in drain_events
    return self._poll(self.cycle, callback, timeout=timeout)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 414, in _poll
    return cycle.get(callback)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/kombu/utils/scheduling.py", line 55, in get
    return self.fun(resource, callback, **kwargs)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 418, in _get_and_deliver
    callback(message, queue)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 1017, in _deliver
    callback(message)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 639, in _callback
    return callback(message)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/kombu/messaging.py", line 656, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 668, in on_task_received
    strategy(
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/worker/strategy.py", line 207, in task_message_handler
    handle(req)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/worker/worker.py", line 225, in _process_task
    req.execute_using_pool(self.pool)
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/worker/request.py", line 754, in execute_using_pool
    result = apply_async(
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/concurrency/base.py", line 153, in apply_async
    return self.on_apply(target, args, kwargs,
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/concurrency/base.py", line 42, in apply_target
    callback(ExceptionInfo())
  File "/home/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/celery/worker/request.py", line 772, in on_success
    failed, retval, runtime = failed__retval__runtime
TypeError: cannot unpack non-iterable ExceptionInfo object
```

It seems that something is parsing the pytest arguments as command line arguments to the conda-store-server command. 

### Expected behavior

The tests should pass

### How to Reproduce the problem?

Run `pytest -v tests`

**Comment by costrouc** [comment]
Yeah it is annoying :frowning:. This was introduced once I added support for running the celery workers in pytest. Would love if this could be debugged and fixed. I always want to pass `-x` to pytest.

**Comment by steff456** [comment]
Hi!! 

I've been trying to reproduce this issue the whole day without any luck. 

When I tried it in the docker image in my macOS computer, I'm able to run `pytest` with arguments without having an error,

<img width="1765" alt="image" src="https://github.com/conda-incubator/conda-store/assets/20992645/6c8dbcfa-0031-45ee-8c86-1888f7dee261">

I also did a clean install in a linux machine and the command is working fine,

![image](https://github.com/conda-incubator/conda-store/assets/20992645/a85e0fed-6011-48f4-b025-5001a9067197)

Just to be sure, I'm running the tests under the `conda-store-server` folder.

**Comment by asmeurer** [comment]
I'm also not reproducing it now. I'm on a different machine, so I'll need to go check the machine I was using when I opened this issue. It's possible it has already been fixed.

**Comment by steff456** [comment]
Let me know! 😉

**Comment by costrouc** [comment]
@steff456 I can reproduce this via

```
cd conda-store-server
pytest tests/test_traitlets.py -x
```

I think important versions

```
pytest-celery 0.0.0a1
celery 5.3.1
```

**Comment by costrouc** [comment]
I also did a `conda env update ....` and was still able to reproduce the issue

**Comment by steff456** [comment]
So I see something curious happening now

- I can reproduce your error with `pytest tests/test_traitlets.py -x` but the error arises in a pytest module
- If I reorganize the command and use `pytest -x tests/test_traitlets.py` it works as expected

I also took some time to go back to a commit before you added celery, and it is happening exactly the same as above. I think pytest flags need to go first.

**Comment by costrouc** [comment]
Yeah that works. @steff456 weird that this happens with the `-x` at the end. Anyways thanks for finding that!

I think this is fine to close

**Comment by steff456** [comment]
Closing this issue! Thanks @costrouc and @asmeurer :)

**Comment by steff456** [comment]
I've always put the flags at the beginning when using pytest 🤷🏻‍♀️

**Comment by asmeurer** [comment]
If you want to rerun the previous test with -x, you typically just add it to the end of the command. 

I don't think this issue should be closed. If this behavior is intended, that arguments passed after the tests dir are forwarded to the commands used in the test, then this should be documented. I couldn't find anything about that in the pytest docs. To me, this indicates an issue in the way the tests are written. The tests should be isolated in such a way that they shouldn't depend on external state, in this case, things that happen to be in sys.argv from an unrelated command.

**Comment by asmeurer** [comment]
With that being said, it's also possible this is an upstream issue with celery.

**Comment by asmeurer** [comment]
If I run `pytest -x tests/test_app_api.py`, I get the warning from stderr:

```
[CondaStoreWorker] WARNING | Unrecognized alias: 'x', it will have no effect.
```

meaning it is still reading `-x`, but it just happens to read in a way that doesn't break the test.

**Comment by steff456** [comment]
After more research and a breakpoint I have the following stack trace,

![image](https://github.com/conda-incubator/conda-store/assets/20992645/80c2abfa-2266-4891-8190-a8043faec343)

Apparently there's an issue with `trailets` and the way they are parsing the arguments. I can go ahead an open an issue for this, but I think there's nothing on our side to fix this.

**Comment by steff456** [comment]
I think I found a workaround for this issue, please check the PR :)

**Comment by asmeurer** [comment]
This is still an issue for me in `main`:

```
$ pytest tests/test_app_api.py -v
========================================================================== test session starts ==========================================================================
platform darwin -- Python 3.10.0, pytest-7.4.2, pluggy-1.3.0 -- /Users/aaronmeurer/anaconda3/envs/conda-store-server-dev/bin/python3.10
cachedir: .pytest_cache
rootdir: /Users/aaronmeurer/Documents/conda-store/conda-store-server
plugins: celery-0.0.0a1, playwright-0.4.2, base-url-2.0.0, mock-3.11.1, anyio-3.7.1
collected 5 items

tests/test_app_api.py::test_conda_store_app_register_solve FAILED                                                                                                 [ 20%]
tests/test_app_api.py::test_conda_store_register_environment_workflow FAILED                                                                                      [ 40%]
tests/test_app_api.py::test_conda_store_register_environment_force_false_same_namespace PASSED                                                                    [ 60%]
tests/test_app_api.py::test_conda_store_register_environment_force_false_different_namespace PASSED                                                               [ 80%]
tests/test_app_api.py::test_conda_store_register_environment_duplicate_force_true PASSED                                                                          [100%]

=============================================================================== FAILURES ================================================================================
__________________________________________________________________ test_conda_store_app_register_solve __________________________________________________________________

[...]

------------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------------
usage: pytest [-h] [--standalone] [--config CondaStoreWorker.config_file]
              [extra_args ...]
pytest: error: argument -v: expected one argument
Restoring 1 unacknowledged message(s)
--------------------------------------------------------------------------- Captured log call ---------------------------------------------------------------------------
CRITICAL celery.worker:worker.py:206 Unrecoverable error: TypeError('cannot unpack non-iterable ExceptionInfo object')
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/argparse.py", line 1853, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/argparse.py", line 2062, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/Users/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/argparse.py", line 1992, in consume_optional
    arg_count = match_argument(action, selected_patterns)
  File "/Users/aaronmeurer/anaconda3/envs/conda-store-server-dev/lib/python3.10/argparse.py", line 2157, in _match_argument
    raise ArgumentError(action, msg)
argparse.ArgumentError: argument -v: expected one argument
[...]
======================================================================== short test summary info ========================================================================
FAILED tests/test_app_api.py::test_conda_store_app_register_solve - celery.exceptions.TimeoutError: The operation timed out.
FAILED tests/test_app_api.py::test_conda_store_register_environment_workflow - celery.exceptions.TimeoutError: The operation timed out.
========================================================== 2 failed, 3 passed, 10 warnings in 98.43s (0:01:38) ==========================================================
```
