### ISSUE TITLE
[BUG] - Pip subdependency PyYAML fails to build 

### ISSUE THREAD

**Issue by kcpevey** [conda-incubator/conda-store#551]
### Describe the bug

When I have a pip package that has the subdependency of PyYAML, pip fails to build pyyaml. I can't tell if this is a conda-store issue or a Nebari issue. 

This is particularly significant because `pyyaml` has a different name on conda. Therefore, I can't satisfy this pip requirement by adding it to my conda environment because pip won't "see" it. Which means I have no other option but to leave the offending package off of my conda spec and install it as a local package with `--no-deps`. 

### Expected behavior

I expect to be able to use pip packages as part of my conda env spec (even though its not recommended). 

### How to Reproduce the problem?

Environment spec:

```
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
      - tf-models-official
  - ipykernel
```

### Output

Traceback:

```
Collecting pyyaml<6.0,>=5.1 (from tf-models-official->-r /tmp/tmp5pef5_8a/condaenv.e__lb1f4.requirements.txt (line 1))
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 175.1/175.1 kB 36.7 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
Pip subprocess error:
  error: subprocess-exited-with-error
  
  Ã— Getting requirements to build wheel did not run successfully.
  â”‚ exit code: 1
  â•°â”€> [68 lines of output]
      /tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
      
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
      
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/home/conda/kcpevey@quansight.com/3e48a96da0fc38ce94ae0d3cc494a39d67c56fb4706f848e13967a2c30e4aef2-20230828-143736-821079-75-goat_test1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/conda/kcpevey@quansight.com/3e48a96da0fc38ce94ae0d3cc494a39d67c56fb4706f848e13967a2c30e4aef2-20230828-143736-821079-75-goat_test1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/conda/kcpevey@quansight.com/3e48a96da0fc38ce94ae0d3cc494a39d67c56fb4706f848e13967a2c30e4aef2-20230828-143736-821079-75-goat_test1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 319, in run
          self.find_sources()
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 327, in find_sources
          mm.run()
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 549, in run
          self.add_defaults()
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 587, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-bdrxu454/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Ã— Getting requirements to build wheel did not run successfully.
â”‚ exit code: 1
â•°â”€> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


failed

CondaEnvException: Pip failed
```

**Comment by steff456** [comment]
After doing some investigation I think the issue with is solving this environment. 

I tried creating this environment in `conda-store-ui` where it fails, but I also try it on my local conda where I see the same error you posted. I think this doesn't seem related to either `conda-store` or `nebari`, it is just that the tarball for `PyYAML` is not able to be constructed and installed in the environment.

I guess the main question is what packages are you needing from `pip` that aren't in the `conda-forge` channel.

**Comment by asmeurer** [comment]
conda packages should include the necessary metadata for pip to know that they are installed (typically the `.dist-info` directory in `site-packages`). If pip doesn't recognize the conda pyyaml package as being installed, that's an issue with that particular package.

**Comment by dharhas** [comment]
> This is particularly significant because pyyaml has a different name on conda.

I'm not sure this is true. conda-forge has a pyyaml & a yaml package.

https://anaconda.org/conda-forge/pyyaml

does installing pyyaml via conda solve this issue?

**Comment by kcpevey** [comment]
I think the capitalization matters here. The subdependency is looking for `PyYAML` and conda-forge has `pyyaml`. So pip doesn't recognize that `PyYAML` is already in my environment as `pyyaml`
