### ISSUE TITLE
[BUG] - Conda-lock / poetry version inconsistency causes solve failures in some cases

### ISSUE THREAD

**Issue by kcpevey** [conda-incubator/conda-store#851]
### Describe the bug

This environment solves locally, but fails on Nebari:

```
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - ragna[all] @ git+https://github.com/Quansight/ragna@one-server
      - panel @
        git+https://github.com/holoviz/panel@7377c9e99bef0d32cbc65e94e908e365211f4421
      - bokeh-fastapi @ git+https://github.com/bokeh/bokeh-fastapi@main
  - ipykernel
```

The root issue here is [conda-lock needs to update its poetry dependency](https://github.com/conda/conda-lock/issues/613). 

This issue is to track that progress and update conda-lock whenever the upstream issue is resolved. 

### Expected behavior

We expect environments that build locally to also build on nebari. 

### How to Reproduce the problem?

See environment above. 

### Output

Traceback:
```
INFO:root:Collecting panel@ git+https://github.com/holoviz/panel@7377c9e99bef0d32cbc65e94e908e365211f4421 (from -r /tmp/tmpuaxz2b9x (line 121))
INFO:root:  Cloning https://github.com/holoviz/panel (to revision 7377c9e99bef0d32cbc65e94e908e365211f4421) to /tmp/pip-install-b3hh2nws/panel_6478e9058dd04a69a17627733b1ae9ea
INFO:root:  Resolved https://github.com/holoviz/panel to commit 7377c9e99bef0d32cbc65e94e908e365211f4421
INFO:root:  Installing build dependencies: started
INFO:root:  Installing build dependencies: finished with status 'done'
INFO:root:  Getting requirements to build wheel: started
INFO:root:  Getting requirements to build wheel: finished with status 'done'
INFO:root:  Preparing metadata (pyproject.toml): started
INFO:root:  Preparing metadata (pyproject.toml): finished with status 'error'
INFO:root:
Traceback (most recent call last):
  File "/opt/conda/envs/conda-store-server/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/conda-store-server/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/conda_lock/__main__.py", line 4, in <module>
    main()
  File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 1497, in click_install
    install(
  File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 1551, in install
    install_func(file=lockfile)
  File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 240, in do_conda_install
    _conda(["run"], ["pip", "install", "--no-deps", "-r", str(requirements_path)])
  File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/conda_lock/invoke_conda.py", line 143, in _invoke_conda
    raise subprocess.CalledProcessError(
conda_lock._vendor.poetry.utils._compat.CalledProcessError: Command '['/opt/conda/condabin/mamba', 'run', '--prefix', '/home/conda/pmeier@quansight.com/9f2935ac-1718179838-776-ragna-dev', 'pip', 'install', '--no-deps', '-r', '/tmp/tmpuaxz2b9x']' returned non-zero exit status 1.
```

**Comment by trallard** [comment]
Noting there might be a release soon-ish https://github.com/conda/conda-lock/issues/725 
so we should think of upgrading once this is out
